name = "GuSTO"
uuid = "ceb88251-baee-58f1-80cf-3a3b27eec344"
keywords = ["trajectory", "optimization", "sequential", "convex", "programming"]
license = "MIT"
desc = "Guaranteed Sequential Trajectory Optimization (GuSTO) framework."
version = "1.0.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Cxx = "a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathOptInterfaceMosek = "0087ddc6-3964-5e57-817f-9937aefb0357"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
MechanismGeometries = "931e9471-e8fb-5385-a477-07ad12718aca"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reactive = "a223df75-4e93-5b7c-acf9-bdd599c0f4de"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
RigidBodySim = "e61f16d8-a6b7-5689-8d03-627c2b27ebce"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
